FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS server
COPY --from=build /usr/src/app /usr/src/app
WORKDIR /usr/src/app
RUN cd ./packages/dtos && pnpm build && cd ../..
EXPOSE 1209
CMD [ "pnpm", "server:migrate-and-run" ]

