export type NotificationType =
    | 'APPLICATION_CREATED'
    | 'APPLICATION_REJECTED'
    | 'APPLICATION_ACCEPTED'
    | 'ORGANIZATION_CREATED'
    | 'ACCOUNT_CLOSED'
    | 'ORGANIZATION_CLOSED'
    | 'STAFF_INVITED'
    | 'RECEIVED_CREDENTIAL'
    | 'CREDENTIAL_CLAIMED'
    | 'ISSUED_CREDENTIAL'
    | 'CREDENTIAL_REVOKED';
